server:
  port: 8080

spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    data: classpath:db/data-h2.sql
    schema: classpath:db/schema-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

#<second> <minute> <hour> <day-of-month> <month> <day-of-week> <year> <command>
#modrun:
#  daily:
#    cron: 0/3 * * * * *
#    fileName: power_consumption_daily_meterno_timestamp.pdf
#  monthly:
#    cron: * * * * * MON-FRI
#    fileName: power_consumption_daily_meterno_timestamp.pdf
#  quarterly:
#    cron:  * * * * * MON-FRI
#    fileName: power_consumption_daily_meterno_timestamp.pdf


